// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeloAPP.Models;

namespace VeloAPP.Migrations
{
    [DbContext(typeof(BicycleAppDBContext))]
    [Migration("20210412205335_migration3")]
    partial class migration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeloAPP.Models.Detail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RamaId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("RamaId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("VeloAPP.Models.Koleso", b =>
                {
                    b.Property<int>("KolesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Radius")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamaId")
                        .HasColumnType("int");

                    b.HasKey("KolesoId");

                    b.HasIndex("RamaId");

                    b.ToTable("Kolesos");
                });

            modelBuilder.Entity("VeloAPP.Models.Rama", b =>
                {
                    b.Property<int>("RamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RamaId");

                    b.ToTable("Ramas");
                });

            modelBuilder.Entity("VeloAPP.Models.Detail", b =>
                {
                    b.HasOne("VeloAPP.Models.Rama", "Ramas")
                        .WithMany("Details")
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ramas");
                });

            modelBuilder.Entity("VeloAPP.Models.Koleso", b =>
                {
                    b.HasOne("VeloAPP.Models.Rama", "Ramas")
                        .WithMany("Kolesos")
                        .HasForeignKey("RamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ramas");
                });

            modelBuilder.Entity("VeloAPP.Models.Rama", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Kolesos");
                });
#pragma warning restore 612, 618
        }
    }
}
